export type EventStatus = "confirmed" | "reported" | "disputed" | "official";

export type Course = {
  id: string;
  code: string;
  name: string;
  section: string;
  color: string;
  followed: boolean;
};

export type TestEvent = {
  id: string;
  courseId: string;
  title: string;
  kind: string;
  date: string;
  start: string | null;
  duration: number;
  section: string;
  room?: string;
  topics?: string;
  source: string;
  sourceDetail: string;
  reporter: string;
  reportedAt: string;
  confirmations: number;
  confirmedByMe: boolean;
  status: EventStatus;
  otherSection?: boolean;
};

export const initialCourses: Course[] = [
  {
    id: "phy-f211",
    code: "PHY F211",
    name: "Classical Mechanics",
    section: "T1",
    color: "#2f6f68",
    followed: true,
  },
  {
    id: "phy-f212",
    code: "PHY F212",
    name: "Electromagnetic Theory I",
    section: "T2",
    color: "#2f5d8a",
    followed: true,
  },
  {
    id: "phy-f213",
    code: "PHY F213",
    name: "Optics",
    section: "T1",
    color: "#9a5b36",
    followed: true,
  },
  {
    id: "math-f211",
    code: "MATH F211",
    name: "Mathematics III",
    section: "T6",
    color: "#6b4f8a",
    followed: true,
  },
  {
    id: "bits-f225",
    code: "BITS F225",
    name: "Environmental Studies",
    section: "L1",
    color: "#4d6b42",
    followed: false,
  },
  {
    id: "gs-f321",
    code: "GS F321",
    name: "Humanities Elective",
    section: "P1",
    color: "#89536a",
    followed: false,
  },
];

export const initialEvents: TestEvent[] = [
  {
    id: "cm-tut-1",
    courseId: "phy-f211",
    title: "Tutorial Test 1",
    kind: "Tut test",
    date: "2026-08-17",
    start: "16:00",
    duration: 30,
    section: "T1",
    room: "6156",
    topics: "Constraints, generalized coordinates, d'Alembert's principle",
    source: "Announced in class",
    sourceDetail: "Professor announced it in Monday's tutorial.",
    reporter: "Aarav M.",
    reportedAt: "14 Aug, 5:42 PM",
    confirmations: 8,
    confirmedByMe: false,
    status: "confirmed",
  },
  {
    id: "math-quiz-1",
    courseId: "math-f211",
    title: "Quiz 1",
    kind: "Quiz",
    date: "2026-08-18",
    start: "08:00",
    duration: 30,
    section: "T6",
    room: "6164",
    topics: "First-order differential equations",
    source: "Google Classroom",
    sourceDetail: "Posted in the Quiz 1 announcement.",
    reporter: "Meera S.",
    reportedAt: "16 Aug, 9:11 PM",
    confirmations: 12,
    confirmedByMe: true,
    status: "official",
  },
  {
    id: "em-quiz",
    courseId: "phy-f212",
    title: "In-class Quiz",
    kind: "Quiz",
    date: "2026-08-19",
    start: "12:00",
    duration: 30,
    section: "L1 + L2",
    room: "6155",
    topics: "Electrostatics and boundary conditions",
    source: "Professor's email",
    sourceDetail: "Course-wide email sent on 17 August.",
    reporter: "Riya K.",
    reportedAt: "17 Aug, 7:26 PM",
    confirmations: 17,
    confirmedByMe: false,
    status: "official",
  },
  {
    id: "optics-tut",
    courseId: "phy-f213",
    title: "Tutorial Test 1",
    kind: "Tut test",
    date: "2026-08-21",
    start: "09:00",
    duration: 30,
    section: "T1",
    room: "6155",
    topics: "Fermat's principle and geometrical optics",
    source: "Announced in tutorial",
    sourceDetail: "Two students reported the same announcement.",
    reporter: "Kabir J.",
    reportedAt: "17 Aug, 10:04 AM",
    confirmations: 5,
    confirmedByMe: false,
    status: "confirmed",
  },
  {
    id: "cm-other",
    courseId: "phy-f211",
    title: "Tutorial Test 1",
    kind: "Other-section signal",
    date: "2026-08-22",
    start: "11:00",
    duration: 30,
    section: "T3",
    room: "6103",
    topics: "Lagrangian formulation",
    source: "Announced in tutorial",
    sourceDetail: "This report applies to T3, not your section T1.",
    reporter: "Devika P.",
    reportedAt: "18 Aug, 8:14 AM",
    confirmations: 2,
    confirmedByMe: false,
    status: "reported",
    otherSection: true,
  },
  {
    id: "math-tut-2",
    courseId: "math-f211",
    title: "Tutorial Test 2",
    kind: "Tut test",
    date: "2026-08-25",
    start: "08:00",
    duration: 30,
    section: "T6",
    room: "6164",
    topics: "Linear systems and eigenvalues",
    source: "Google Classroom",
    sourceDetail: "Date included in Tutorial Sheet 2 post.",
    reporter: "Ishaan B.",
    reportedAt: "18 Aug, 11:32 AM",
    confirmations: 6,
    confirmedByMe: false,
    status: "confirmed",
  },
  {
    id: "cm-tut-2",
    courseId: "phy-f211",
    title: "Tutorial Test 2",
    kind: "Tut test",
    date: "2026-08-31",
    start: "16:00",
    duration: 30,
    section: "T1",
    room: "6156",
    topics: "Central-force motion and effective potential",
    source: "Announced in class",
    sourceDetail: "Reported after Friday's lecture.",
    reporter: "Nandini R.",
    reportedAt: "28 Aug, 4:18 PM",
    confirmations: 3,
    confirmedByMe: false,
    status: "reported",
  },
  {
    id: "em-test-2",
    courseId: "phy-f212",
    title: "Tutorial Test 2",
    kind: "Tut test",
    date: "2026-09-04",
    start: "13:00",
    duration: 30,
    section: "T2",
    room: "6152",
    topics: "Laplace equation and image method",
    source: "Announced in tutorial",
    sourceDetail: "Date reported independently by three students.",
    reporter: "Sana A.",
    reportedAt: "1 Sep, 6:03 PM",
    confirmations: 4,
    confirmedByMe: false,
    status: "confirmed",
  },
  {
    id: "midsem-phy",
    courseId: "phy-f211",
    title: "MidSemester Examination",
    kind: "MidSem",
    date: "2026-10-08",
    start: null,
    duration: 90,
    section: "All sections",
    topics: "As defined in the course handout",
    source: "AUGSD timetable",
    sourceDetail: "Official course-wide date.",
    reporter: "Official import",
    reportedAt: "1 Aug",
    confirmations: 0,
    confirmedByMe: false,
    status: "official",
  },
  {
    id: "compre-phy",
    courseId: "phy-f211",
    title: "Comprehensive Examination",
    kind: "Compre",
    date: "2026-12-12",
    start: null,
    duration: 180,
    section: "All sections",
    topics: "Full course",
    source: "AUGSD timetable",
    sourceDetail: "Official course-wide date.",
    reporter: "Official import",
    reportedAt: "1 Aug",
    confirmations: 0,
    confirmedByMe: false,
    status: "official",
  },
];
